import { Inter } from "next/font/google";
import { Syne } from "next/font/google";
import { Advent_Pro } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const syne = Syne({
  subsets: ["latin"],
  variants: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-display-syne",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${syne.className}`}>{children}</body>
    </html>
  );
}
